hopefully working

diff --git a/ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2 b/ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2
--- a/ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2
+++ b/ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2
@@ -11,72 +11,106 @@ NC='\033[0m' # No Color
 bold=$(tput bold)
 normal=$(tput sgr0)
 
-function copy_logs
-{
-    # copy logs to temp folder
-    docker exec $container_name bash -c "mkdir /home/user/logs_temp/" || true
-    docker exec $container_name bash -c "cp /home/user/.ros/log/stderr.log /home/user/logs_temp/" || true
-    docker exec $container_name bash -c "rm /home/user/.ros/log/std*.log" || true
-    docker exec $container_name bash -c "cp /home/user/.ros/log/core_dumps/* /home/user/logs_temp/" || true
-    docker exec $container_name bash -c "rm /home/user/.ros/log/core_dumps/core_*" || true
-    docker exec $container_name bash -c "cp /home/user/.ros/log/latest/* /home/user/logs_temp/"  || true
-    docker exec $container_name bash -c "cp $latestbag /home/user/logs_temp/"  || true
-    docker exec $container_name bash -c "cp $latestparam /home/user/logs_temp/"  || true
-    docker exec $container_name bash -c "cp $latestws /home/user/logs_temp/"  || true
-    docker cp -L ${ros_log_dir}/$dir/ros_log_$timestamp/notes_from_user.txt $container_name:/home/user/logs_temp/
-    docker cp -L ${ros_log_dir}/$dir/ros_log_$timestamp/container_info.txt $container_name:/home/user/logs_temp/
-    docker cp -L ${ros_log_dir}/$dir/ros_log_$timestamp/image_info.txt $container_name:/home/user/logs_temp/
-}
-function copy_to_host
-{
-    echo "Copying logs from docker container to host..."
-    docker cp -L $container_name:/home/user/logs_temp ${ros_log_dir}/$dir/ros_log_$timestamp/
-    mv ${ros_log_dir}/$dir/ros_log_$timestamp/logs_temp/* ${ros_log_dir}/$dir/ros_log_$timestamp/
-    rm -rf ${ros_log_dir}/$dir/ros_log_$timestamp/logs_temp
-}
-function copy_rosbag
-{
-    latestws=$(docker exec $container_name bash -c 'ls -dtr /home/user/wsdiff_ws_diff* | tail -1')
-    latestparam=$(docker exec $container_name bash -c 'ls -dtr /home/user/run_params* | tail -1')
-	docker exec $container_name /ros_entrypoint.sh bash -c "rosnode kill /record" || true
-    sleep 1
-	latestbag=$(docker exec $container_name bash -c 'ls -dtr /home/user/*.bag | tail -1') || true
-    echo "Copying logs from $container_name..."
-}
-function copy_coredump
-{
-    core_name=$(docker exec $container_name bash -c "ls /home/user/.ros/log/core_dumps/core* | grep -v '\.log' | awk '{if(NR>0) print $NF}'")
-        if [ ! -z "$core_name" ]; then
-            core_array=($core_name)
-            for core in ${!core_array[@]}; do
-                current_core=${core_array[$core]}
-                current_runtime=$(docker exec $container_name bash -c "echo $current_core | grep -o -P '(?<=core_BOF_).*(?=_EOF_)'")
-                runtime_name=$(docker exec $container_name bash -c "strings $current_core | grep $current_runtime | tail -1")
-                #use runtime name in the log file to use later
-                docker exec $container_name bash -c "echo 'Executable:' $runtime_name > $current_core.log" || true
-                #extract readable info to log file
-                docker exec $container_name bash -c "gdb --core=$current_core $runtime_name -ex 'bt full' -ex 'quit' >> $current_core.log" || true
-            done
-        fi
-}
-function copy_container_and_image_info
-{
-    # get container and image info
-    container_image=$(docker ps -a | grep $container_name | awk '{print $2}' | tail -1)
-    docker container inspect $container_name > ${ros_log_dir}/$dir/ros_log_$timestamp/container_info.txt
-    docker images $container_image > ${ros_log_dir}/$dir/ros_log_$timestamp/image_info.txt
-}
-
+#default values - some are temporarily overridden in ssh sessions later on
+docker_user_home="/home/user"
+docker_ros_folder="$docker_user_home/.ros"
+docker_logs_temp="$docker_user_home/logs_temp"
+docker_ros_logs_folder="$docker_ros_folder/log/"
+record_node="/record"
 container_name={{ container_name }}
 save_nuc_logs={{ save_nuc_logs | lower }} 
 NUC_NAME={{ nuc_username }}
 NUC_ADDRESS={{ nuc_address }}
+local_ros_log_dir=~/Desktop/ROS_LOGS/$container_name
+local_ros_date_directory=ros_logs_$(date +%Y-%m-%d)
+timestamp=$(date +%Y-%m-%d-%T)
+computer_name=""
 
-info_message="You are about to save latest ros logs from this computer"
-warning_message="WARNING! This closes the {{ container_name }} docker container in this computer. Do you wish to continue? (Y/n) "
+function copy_logs
+{
+    echo "Copying logs from $docker_ros_folder to $docker_logs_temp inside the $container_name Docker container on $HOSTNAME"
+    if computer_name=="server"; then
+        record_node="/server_record"
+    fi
+    if computer_name=="server"; then
+        record_node="/control_box/record"
+    fi
+    docker exec $container_name /ros_entrypoint.sh bash -c "rosnode kill $record_node" || true
+    sleep 1
+    latestbag=$(docker exec $container_name bash -c 'ls -dtr $docker_ros_folder/*.bag | tail -1') || true
+    docker exec $container_name bash -c "mkdir $docker_logs_temp" || true
+    docker exec $container_name bash -c "cp $docker_ros_logs_folder/stderr.log $docker_logs_temp" || true
+    docker exec $container_name bash -c "rm $docker_ros_logs_folder/std*.log" || true
+    core_name=$(docker exec $container_name bash -c "ls $docker_ros_logs_folder/core_dumps/core* | grep -v '\.log' | awk '{if(NR>0) print $NF}'")
+    if [ ! -z "$core_name" ]; then
+        core_array=($core_name)
+        for core in ${!core_array[@]}; do
+            current_core=${core_array[$core]}
+            current_runtime=$(docker exec $container_name bash -c "echo $current_core | grep -o -P '(?<=core_BOF_).*(?=_EOF_)'")
+            runtime_name=$(docker exec $container_name bash -c "strings $current_core | grep $current_runtime | tail -1")
+            #use runtime name in the log file to use later
+            docker exec $container_name bash -c "echo 'Executable:' $runtime_name > $current_core.log" || true
+            #extract readable info to log file
+            docker exec $container_name bash -c "gdb --core=$current_core $runtime_name -ex 'bt full' -ex 'quit' >> $current_core.log" || true
+        done
+    fi
+    docker exec $container_name bash -c "cp $docker_ros_logs_folder/core_dumps/* $docker_logs_temp" || true
+    docker exec $container_name bash -c "rm $docker_ros_logs_folder/core_dumps/core_*" || true
+    docker exec $container_name bash -c "cp $docker_ros_logs_folder/latest/* $docker_logs_temp"  || true
+    latestws=$(docker exec $container_name bash -c 'ls -dtr $docker_ros_folder/wsdiff_ws_diff* | tail -1')
+    latestparam=$(docker exec $container_name bash -c 'ls -dtr $docker_ros_folder/run_params* | tail -1')
+    docker exec $container_name bash -c "cp $latestbag $docker_logs_temp"  || true
+    docker exec $container_name bash -c "cp $latestparam $docker_logs_temp"  || true
+    docker exec $container_name bash -c "cp $latestws $docker_logs_temp"  || true
+    container_image=$(docker ps -a | grep $container_name | awk '{print $2}' | tail -1)
+    docker container inspect $container_name > $docker_logs_temp/container_info.txt
+    docker images $container_image > $docker_logs_temp/image_info.txt
+}
+function copy_to_host
+{
+    mkdir -p ${local_ros_log_dir}/$dir/ros_log_$timestamp
+    echo "Copying logs $docker_logs_temp folder in $container_name Docker container to host $HOSTNAME local folder $local_ros_log_dir"
+    docker cp -L $container_name:$docker_logs_temp ${local_ros_log_dir}/$dir/ros_log_$timestamp/
+    mv ${local_ros_log_dir}/$dir/ros_log_$timestamp/logs_temp/* ${local_ros_log_dir}/$dir/ros_log_$timestamp/
+    rm -rf ${local_ros_log_dir}/$dir/ros_log_$timestamp/logs_temp
+}
+function scp_nuc_to_server
+{
+    echo "Copying files from control machine to teleop server"
+    scp -r $NUC_NAME@$NUC_ADDRESS:$docker_user_home/ROS_LOGS/$container_name/$dir/ros_log_$timestamp/ $local_ros_log_dir/control_machine/$dir/ros_log_$timestamp/
+}
+function save_all_logs
+{
+    copy_logs
+    copy_to_host
+    if save_nuc_logs; then
+        ssh $NUC_NAME@$NUC_ADDRESS container_name=$container_name 'bash -s' < ENDSSH
+        container_name={{ container_name }}
+        save_nuc_logs={{ save_nuc_logs | lower }} 
+        NUC_NAME={{ nuc_username }}
+        NUC_ADDRESS={{ nuc_address }}
+        local_ros_date_directory=ros_logs_$(date +%Y-%m-%d)
+        timestamp=$(date +%Y-%m-%d-%T)
+        computer_name="control_machine"
+        docker_user_home="/home/user"
+        docker_ros_folder="$docker_user_home/.ros"
+        docker_logs_temp="$docker_user_home/logs_temp"
+        docker_ros_logs_folder="$docker_ros_folder/log/"
+        local_ros_log_dir=$docker_user_home/ROS_LOGS/$container_name
+        dir=ros_logs_$(date +%Y-%m-%d)
+        $(typeset -f)
+        copy_logs   
+        copy_to_host
+        ENDSSH
+    fi
+}
+
+info_message="You are about to save latest ROS logs from $container_name Docker container on this computer ($HOSTNAME)"
+warning_message="WARNING! This closes the $container_name docker container in this computer. Do you wish to continue? (Y/n) "
 if save_nuc_logs; then
-    info_message="You are about to save latest ros logs from this machine and the control computer"
-    warning_message="WARNING! This closes the {{ container_name }} docker container in both this and the control computer. Do you wish to continue? (Y/n) "
+    info_message="You are about to save latest ROS logs from $container_name Docker containers on teleop server and control computer"
+    warning_message="WARNING! This closes the $container_name Docker containers in this and the control computer. Do you wish to continue? (Y/n) "
+    computer_name="server"
 fi
 
 echo -e "${NC}${normal}${info_message}${normal}${NC}"
@@ -89,6 +123,8 @@ fi
 
 echo -e "${NC}${normal}Please add a note for logging with reasons... ${normal}${NC}"
 read notes_from_user
+mkdir -p $local_ros_log_dir
+echo $notes_from_user > $local_ros_log_dir/notes_from_user.tx
 
 if [ "$(docker exec ${container_name} bash -c 'ls /usr/local/bin/customer.key')" ]; then
     save_log_msg_config_file="/home/$USER/.shadow_save_log_app/save_sr_log_msg_config.cfg"
@@ -151,22 +187,19 @@ if [ ! -z "$container_name" ]; then
     else
         customer_key=false
     fi
-    ros_log_dir=~/Desktop/ROS_LOGS/$container_name
-    dir=ros_logs_$(date +%Y-%m-%d)
-    timestamp=$(date +%Y-%m-%d-%T)
-    mkdir -p ${ros_log_dir}/$dir/ros_log_$timestamp
-    echo $notes_from_user > ${ros_log_dir}/$dir/ros_log_$timestamp/notes_from_user.txt
-    copy_rosbag
-    copy_coredump
-    copy_container_and_image_info
+
+    if [ computer_name!="" ]; then
+        local_ros_log_dir="$local_ros_log_dir/$computer_name"
+    fi
+
     if [ ${customer_key} ]; then
         # check if the folder is empty.
-        if [ ! -z "$(docker exec ${container_name} bash -c 'find /home/user/logs_temp -maxdepth 0 -type d 2>/dev/null')" ]; then
+        if [ ! -z "$(docker exec ${container_name} bash -c 'find $docker_logs_temp -maxdepth 0 -type d 2>/dev/null')" ]; then
             echo -e "${YELLOW}${bold}There are previous logs that havent been sent yet. Would you like to send them now? Type 'Y' to send or 'n' to ignore and overwrite them ${normal}${NC}"
             read old_logs
             if [[ $old_logs == "y" || $old_logs == "Y" || $old_logs == "yes" || $old_logs == "Yes" || $old_logs == "YES" ]]; then
                 echo "Uploading to Shadow servers - Please wait..."
-                upload_command=$(docker exec $container_name bash -c "source /usr/local/bin/shadow_upload.sh ${customer_key} /home/user/logs_temp $timestamp" || true) 
+                upload_command=$(docker exec $container_name bash -c "source /usr/local/bin/shadow_upload.sh ${customer_key} $docker_logs_temp $timestamp" || true) 
                 if [[ $upload_command == "ok" ]]; then
                     echo -e "${GREEN} Previous logs Uploaded to Shadow servers for $container_name! ${NC}"
                 else
@@ -177,53 +210,38 @@ if [ ! -z "$container_name" ]; then
 		        sleep 1
             fi
             # delete temp folder
-            docker exec $container_name bash -c "rm -rf /home/user/logs_temp"
+            docker exec $container_name bash -c "rm -rf $docker_logs_temp"
         fi
-    fi
-    # copy new logs to temp folder
-    copy_logs
-    copy_to_host
-    if save_nuc_logs; then
-        ssh $NUC_NAME@$NUC_ADDRESS CONTAINER=$container_name 'bash -s' <<'ENDSSH'
-        $(typeset -f copy_logs)
-        $(typeset -f copy_to_host)
-        $(typeset -f copy_rosbag)
-        $(typeset -f copy_coredump)
-        $(typeset -f copy_container_and_image_info)
-
-        copy_rosbag
-        copy_coredump
-        copy_container_and_image_info
-        copy_logs   
-        copy_to_host
-
-        scp to teleop server
-        ENDSSH
-    fi
-    if [[ $upload_sr_log_messages == "true" ]]; then
-        echo "Uploading to Shadow servers - Please wait..."
-        upload_command=$(docker exec $container_name bash -c "source /usr/local/bin/shadow_upload.sh ${customer_key} /home/user/logs_temp $timestamp" || true)
-        if [[ $upload_command == "ok" ]]; then
-            # delete temp folder
-            docker exec $container_name bash -c "rm -rf /home/user/logs_temp"
-            echo -e "${GREEN} Latest Logs Saved and Uploaded to Shadow servers for $container_name! ${NC}"
-        else
-            echo -e "${RED}${bold} Failed to upload logs to Shadow servers for $container_name! Check your internet connection and try again.${normal}${NC}"
-            sleep 5
+        save_all_logs
+        if save_nuc_logs; then
+            scp_nuc_to_server
         fi
-        sleep 1
-    fi
+        if [[ $upload_sr_log_messages == "true" ]]; then
+            echo "Uploading to Shadow servers - Please wait..."
+            upload_command=$(docker exec $current_container_name bash -c "source /usr/local/bin/shadow_upload.sh ${customerkey} $docker_logs_temp $timestamp" || true)
+            if [[ $upload_command == "ok" ]]; then
+                # delete temp folder
+                docker exec $current_container_name bash -c "rm -rf $docker_logs_temp"
+                echo -e "${GREEN} Latest Logs Saved and Uploaded to Shadow servers for $current_container_name! ${NC}"
+            else
+                echo -e "${RED}${bold} Failed to upload logs to Shadow servers for $current_container_name! Check your internet connection and try again.${normal}${NC}"
+                sleep 5
+            fi
+            sleep 1
+        fi
     else
-        copy_logs
-        copy_to_host
-        docker exec $container_name bash -c "rm -rf /home/user/logs_temp"
+        save_all_logs
+        if save_nuc_logs; then
+            scp_nuc_to_server
+        fi
+        docker exec $container_name bash -c "rm -rf $docker_logs_temp"
         echo -e "${GREEN} Latest Logs Saved for $container_name! ${NC}"
         sleep 1
     fi
     echo "Killing container $container_name..."
     docker kill $container_name
 else
-    echo -e "${RED}There is no docker container running, please start a container to save logs${NC}"
+    echo -e "${RED}There is no $container_name Docker container running, please start a container to save logs${NC}"
     sleep 1
     exit 1
 fi
