B dont ask login for public git (#612)
* Update run-ansible.sh

* Update run-ansible.sh

* Update run-ansible.sh

* testing what happens if we don't auth ssh

* fixes

* add workaround for rate limiting

* still testing

* try passing var

* try with external var

* testing

* seems to work (need to test ssh end of things for private repos

* Update run-ansible.sh

* Update run-ansible.sh

* trigger pr checks again

* debugging failing test

* debugging

* trigger pr checks

* plz do something

* debugging

* tidying

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* tidying and trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

* trying to trigger rate limit

---------

Co-authored-by: carebare47 <tom@shadowrobot.com>
Co-authored-by: Build Tools <build.tools@example.com>
Co-authored-by: Nikolaus Holmes <143398822+niko-holmes@users.noreply.github.com>
Co-authored-by: rnzenha-s <107403736+rnzenha-s@users.noreply.github.com>

diff --git a/ansible/roles/products/common/resources/templates/scripts/pull-pr-branches-and-catkin-make.j2 b/ansible/roles/products/common/resources/templates/scripts/pull-pr-branches-and-catkin-make.j2
--- a/ansible/roles/products/common/resources/templates/scripts/pull-pr-branches-and-catkin-make.j2
+++ b/ansible/roles/products/common/resources/templates/scripts/pull-pr-branches-and-catkin-make.j2
@@ -1,20 +1,29 @@
 #! /bin/bash
 set -e
 source /home/user/projects/shadow_robot/base/devel/setup.bash
+
 PR_BRANCHES="{{ pr_branches_value }}"
-eval $(ssh-agent)
-ssh_test=$(ssh -oStrictHostKeyChecking=no -T git@github.com 2>&1 &)
-results=""
-if [[ "$ssh_test" == *"You've successfully authenticated"* ]]; then
-    echo " ---------------------------------"
-    echo "Github SSH key successfully added!"
-    echo " ---------------------------------"
+SKIP_GIT_SSH_AUTH="{{ skip_git_ssh_auth }}"
+
+if [[ $SKIP_GIT_SSH_AUTH != "true" ]]; then
+    eval $(ssh-agent)
+    ssh_test=$(ssh -oStrictHostKeyChecking=no -T git@github.com 2>&1 &)
+    results=""
+    if [[ "$ssh_test" == *"You've successfully authenticated"* ]]; then
+        echo " ---------------------------------"
+        echo "Github SSH key successfully added!"
+        echo " ---------------------------------"
+    else
+        echo " -------------------------------------------------------"
+        echo "Github SSH authentication failed with message: $ssh_test"
+        echo " -------------------------------------------------------"
+        exit 1
+    fi
 else
-    echo " -------------------------------------------------------"
-    echo "Github SSH authentication failed with message: $ssh_test"
-    echo " -------------------------------------------------------"
-    exit 1
+    eval $(ssh-agent)
 fi
+
+
 for i in $PR_BRANCHES; do
     repo=""
     ros_repo=""
