Added warning to Unimanual Launching of Bimanual Hand and Arm system (#541)
* Added system check role.

* Added bimanual scene information, commented out until the scenes are ready.

* updated year.

* Added a warning for launching unimanual.

* Fixed typo

* Fixed typo

* Changed the template for scene to stop it from executing the role below it.

* Fixed the j2 template.

* Adjusted the warning>

* No arm demos with bimanual

* Fixed merge conflicts.

* Made the message a variable instead of hardcoded.

* fixed typo

* Added the two missing bimanual conditions from demo icons.

* added missing newline.

* Updated error message.

* Swapped quotes.

* Fixed formatting.

* Removed duplicate role call, renamed old call name.

* Refactored scene selection process to include new unimanual scenes for bimanual launch.

* Added warning to teleop

* Fixed simulation inventory issue.

* Added warning to teleop.

* Fixed scene issue.

* Removed duped code.

* Made all bimanual|lower instead of mix of bimanual|bool

* Fixed issue where default wasn't set.

* Added skip_warning var for Aurora Tests

* Added default for enable_warning_var

* Added check to advanced launchers.

* Fixed unassigned var

* Fixed issue with failing role

* Fixed missing arg.

* Fixed icon issue.

* Fixed nuc.

* Made it so warning wouldn't appear during unimanual.

* Fixed mistake.

* Fixed unimanual launch for teleop.

* Made the space only appear if you actually set extra_vars_value

* Pulled upstream. Updated warning.

* Removed dbus command. not installed by default. This command doesn't work on fresh pcs.

* Added brices comments.

* Updated year.

* Ignored error with docker.sock

* Made test use source version.

* Updated args.

* Used correct source version.

* More tests.

* Moved when command.

* Made the reinstall stage get skipped.

* Updated all failing checks to use current branch.

* Fixed variable name missmatch.

---------

Co-authored-by: Beatriz Leon <beatriz@shadowrobot.com>

diff --git a/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop.j2 b/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop.j2
--- a/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop.j2
+++ b/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop.j2
@@ -3,6 +3,15 @@
 
 CONST_TIMEOUT=20
 
+if {{ enable_warning | lower }}; then
+  zenity --warning --title="{{ warning_title }}" --text="{{ warning_text }}" --ok-label="I accept the risks" --extra-button="I decline the risks" --no-wrap --width=400 --height=120
+  response=$?
+  if [ $response -ne 0 ]; then
+      echo "User has declined the risks. Aborting script."
+      exit 1
+  fi
+fi
+
 terminator --geometry "{{ term_1 }}" -T 'Launching server container...' -e "{{ shadow_hand_launcher_folder}}/shadow_server_container.sh"
 
 elapsed_time=0
diff --git a/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2 b/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2
--- a/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2
+++ b/ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2
@@ -4,6 +4,23 @@ NUC_NAME={{ nuc_username }}
 NUC_ADDRESS={{ nuc_address }}
 LOCAL_IP={{ server_ip }}
 
+default_value=1
+if [ $# -eq 1 ]; then
+  enable_warning=$1
+else
+  enable_warning=$default_value
+fi
+
+if [ $enable_warning -eq 0 ]; then
+  zenity --warning --title="{{ warning_title }}" --text="{{ warning_text }}" --ok-label="I accept the risks" --extra-button="I decline the risks" --no-wrap --width=400 --height=120
+  response=$?
+  if [ $response -ne 0 ]; then
+      echo "User has declined the risks. Aborting script."
+      {{ shadow_hand_launcher_folder}}/close_everything.sh
+      exit 1
+  fi
+fi
+
 chrony_status=$(ssh {{ nuc_username }}@{{ nuc_address }} chronyc -n tracking | grep {{ server_ip }} | wc -l)
 if [ $chrony_status -eq 0 ]; then
     echo "NUC lost chrony tracking. Restarting chrony on server and NUC..."
