Added a warning for launching unimanual.

diff --git a/ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything.j2 b/ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything.j2
--- a/ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything.j2
+++ b/ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything.j2
@@ -3,6 +3,15 @@
 
 CONST_TIMEOUT=20
 
+if [ {{ enable_warning }}]; then
+  zenity --warning --title="Unimanual Launch Warning" --text="It is unsafe to use the unimanual system on its own.\n\nBy clicking 'I accept the risks', you acknowledge that you understand the risks involved and take full responsibility for any consequences that may arise." --ok-label="I accept the risks" --no-wrap --width=400 --height=200
+  response=$?
+  if [ $response -ne 0 ]; then
+      echo "User has declined the risks. Aborting script."
+      exit 1
+  fi
+fi
+
 terminator --geometry "{{ term_1 }}" -T 'Launching server container...' -e "{{ shadow_hand_launcher_folder}}/shadow_server_container.sh"
 
 elapsed_time=0
